# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools-display
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  ui:
    input:
      variables:
        project_id:
          name: project_id
          title: Project Id
          invisible: true
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        source_image:
          name: source_image
          title: Image version
          enumValueLabels:
            - label: wordpress-v20240121
              value: projects/click-to-deploy-images/global/images/wordpress-v20240121
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
        machine_type:
          name: machine_type
          title: Machine type
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone
        boot_disk_type:
          name: boot_disk_type
          title: Boot disk type
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone
        boot_disk_size:
          name: boot_disk_size
          title: Boot disk size in GB
          min: 20
          max: 10000
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
            gceDiskSize:
              diskTypeVariable: boot_disk_type
        zone:
          name: zone
          title: Zone
          xGoogleProperty:
            type: ET_GCE_ZONE
        networks:
          name: networks
          title: Network name
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_NETWORK
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
        sub_networks:
          name: subnetworks
          title: Subnetwork name
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_SUBNETWORK
            zoneProperty: zone
            gceSubnetwork:
              networkVariable: networks
        external_ips:
          name: external_ips
          title: External IP
          tooltip: 'An external IP address associated with this instance. Selecting "None" will result in the instance having no external internet access. <a href="https://cloud.google.com/compute/docs/configure-instance-ip-addresses">Learn more</a>'
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_EXTERNAL_IP
            gceExternalIp:
              networkVariable: networks
              notConfigurable: false
              allowStaticIps: true
        enable_tcp_80:
          name: enable_tcp_80
          title: Allow HTTP traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        tcp_80_source_ranges:
          name: tcp_80_source_ranges
          title: Source IP ranges for HTTP traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_80
        enable_tcp_443:
          name: enable_tcp_443
          title: Allow HTTPS traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        tcp_443_source_ranges:
          name: tcp_443_source_ranges
          title: Source IP ranges for HTTPS traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_443
        adminEmailAddress:
          name: adminEmailAddress
          title: Administrator e-mail address
          tooltip: The e-mail address used to create the administrator account for WordPress.
          placeholder: user@example.com
          regexValidation: ^[a-zA-Z0-9!#$%&\'*+\/=?^_`{|}~\.-]+@[a-zA-Z0-9](?:[a-zA-Z0-9]?[.-]?[a-zA-Z0-9]+)+[[a-zA-Z0-9]{1}$
          validation: Please enter a valid email address
          xGoogleProperty:
            type: ET_EMAIL_ADDRESS
        installphpmyadmin:
          name: installphpmyadmin
          title: Install phpMyAdmin
          subtext: phpMyAdmin is an open source tool to administer MySQL databases with the use of a web browser.
        httpsEnabled:
          name: httpsEnabled
          title: HTTPS Enabled
          subtext: Enabled HTTPS communication.
        enable_cloud_logging:
          name: enable_cloud_logging
          title: Enable Cloud Logging
          tooltip: 'Cloud Logging allows you to store, search, analyze, monitor, and alert on log data and events. <a href="https://cloud.google.com/logging/">Learn more</a>'
          section: google_cloud_operations
        enable_cloud_monitoring:
          name: enable_cloud_monitoring
          title: Enable Cloud Monitoring
          tooltip: 'Cloud Monitoring provides visibility into the performance, uptime, and overall health of cloud-powered applications. <a href="https://cloud.google.com/monitoring/">Learn more</a>'
          section: google_cloud_operations
      sections:
        - name: boot_disk
          title: Boot Disk
          tooltip: Each instance requires a disk to boot from.
        - name: networking
          title: Networking
        - name: google_cloud_operations
          title: Google Cloud Operations
          subtext: Monitoring and management for services, containers, applications, and infrastructure
    runtime:
      suggestedActions:
        - heading: Access the phpMyAdmin web interface
          description: Visit phpMyAdmin at http://{vmIp}/phpmyadmin
