# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools-example-wordpress
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-canonical-mp
    source:
      repo: https://github.com/GoogleCloudPlatform/marketplace-tools.git
      sourceType: git
      dir: /examples/terraform/custom/examples/wordpress
    version: 0.0.1
    actuationTool:
      flavor: Terraform
      version: '>= 0.13'
    description:
      tagline: WordPress Google Click to Deploy Solution
      detailed: This module deploys a WordPress Google Click to Deploy Solution from Marketplace.
      preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
    deploymentDuration:
      configurationSecs: 60
      deploymentSecs: 300
    costEstimate:
      description: Wordpress cost details
      url: https://cloud.google.com/products/calculator#id=d2a82f67-ff05-4179-9e15-9682ef77a663
    cloudProducts:
    - productId: Compute Engine
      pageUrl: compute
    author:
      title: click-to-deploy-images
    softwareGroups:
    - type: SG_OS
      software:
      - title: Debian
        version: "11.6"
    - software:
      - title: Apache2
        version: 2.4.56
      - title: MySQL-Client
        version: 8.0.32
      - title: MySQL-Community-Client
        version: 8.0.32
      - title: MySQL-Community-Server
        version: 8.0.32
      - title: MySQL-Server
        version: 8.0.32
      - title: PHP
        version: 8.1.17
      - title: WP-CLI
        version: 2.7.1
      - title: WordPress
        version: "6.2"
      - title: phpMyAdmin
        version: 5.0.2
  content:
    architecture:
      diagramUrl: assets/wp-architecture.png
      description:
      - 1. Clients request content by querying the web url.
      - 2. Requests reach GCP via a public IP and are evaluated by the firewall.
      - 3. Valid requests pass through the firewall and reach the wordpress GCE instance to serve content.
    documentation:
    - title: Hosting a Static Website
      url: https://cloud.google.com/storage/docs/hosting-static-website
  interfaces:
    variables:
    - name: boot_disk_size
      description: The boot disk size for the VM instance in GBs
      varType: string
      defaultValue: "10"
    - name: boot_disk_type
      description: The boot disk type for the VM instance.
      varType: string
      defaultValue: pd-standard
    - name: enable_https
      description: Enabled HTTPS communication for Wordpress
      varType: bool
      defaultValue: false
    - name: enable_logging
      description: Enable cloud logging for the VM instance.
      varType: bool
      required: true
    - name: enable_monitoring
      description: Enable cloud monitoring for the VM instance.
      varType: bool
      required: true
    - name: enable_tcp_443
      description: Enable network traffic over port 443 for Wordpress
      varType: bool
      defaultValue: false
    - name: enable_tcp_80
      description: Enable network traffic over port 80 for Wordpress
      varType: bool
      defaultValue: false
    - name: external_ips
      description: The external IPs assigned to the VM for public access.
      varType: list(string)
      defaultValue:
      - EPHEMERAL
    - name: goog_cm_deployment_name
      description: The name of the deployment and VM instance.
      varType: string
      required: true
    - name: install_phpmyadmin
      description: Install phpMyAdmin on the VM instance
      varType: bool
      defaultValue: true
    - name: machine_type
      description: The machine type to create, e.g. e2-small
      varType: string
      defaultValue: n2-standard-4
    - name: networks
      description: The network name to attach the VM instance.
      varType: list(string)
      defaultValue:
      - default
    - name: project_id
      description: The ID of the project in which to provision resources.
      varType: string
      required: true
    - name: source_image
      description: The image name for the disk for the VM instance.
      varType: string
      defaultValue: projects/click-to-deploy-images/global/images/wordpress-v20220821
    - name: sub_networks
      description: The sub network name to attach the VM instance.
      varType: list(string)
      defaultValue:
      - default
    - name: tcp_443_ip_source_ranges
      description: A comma separated string of source IP ranges for accessing the VM instance over HTTPS port 443.
      varType: string
      required: true
    - name: tcp_80_ip_source_ranges
      description: A comma separated string of source IP ranges for accessing the VM instance over HTTP port 80.
      varType: string
      required: true
    - name: wp_admin_email
      description: The email address for Wordpress admin.
      varType: string
      required: true
    - name: zone
      description: The zone for the solution to be deployed.
      varType: string
      defaultValue: us-west1-a
    outputs:
    - name: admin_password
      description: Password for the admin user
    - name: admin_user
      description: Admin username for Wordpress
    - name: has_external_ip
      description: Flag to indicate if the wordpress machine has an external IP
    - name: instance_machine_type
      description: Machine type for the wordpress compute instance
    - name: instance_nat_ip
      description: Machine type for the wordpress compute instance
    - name: instance_network
      description: Machine type for the wordpress compute instance
    - name: instance_self_link
      description: Self-link for the Wordpress compute instance
    - name: instance_zone
      description: Zone for the wordpress compute instance
    - name: mysql_password
      description: Password for the MySql user
    - name: root_password
      description: Password for the root user
