# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DeploymentManagerTemplate specifies the location that a deployment manager
# template is generated when `mpdev apply` is invoked
apiVersion: dev.marketplace.cloud.google.com/v1alpha1
kind: DeploymentManagerTemplate
metadata:
  name: dmtemplate
deploymentManagerRef:
  group: dev.marketplace.cloud.google.com
  kind: DeploymentManagerAutogenTemplate
  name: autogen
zipFilePath: template.zip # {"$kpt-set":"zipPath"}
---
# DeploymentManagerAutogenTemplate auto-generates a deployment manager template
# that can be deployed using `gcloud deployments create ...`
apiVersion: dev.marketplace.cloud.google.com/v1alpha1
kind: DeploymentManagerAutogenTemplate
metadata:
  name: autogen
spec:
  # See https://pkg.go.dev/github.com/GoogleCloudPlatform/marketplace-tools/mpdev/internal/apply?tab=doc#PackageInfo
  packageInfo:
    version: '1.2.0'
    osInfo:
      name: Debian
      version: '10.10'
    components:
    - name: Google-Fluentd
      version: 1.8.9
    - name: MariaDB
      version: 10.5.11
    - name: Stackdriver-Agent
      version: 6.1.3
  # See https://github.com/GoogleCloudPlatform/marketplace-tools/docs/autogen-reference.md
  # for explanation of fields
  deploymentSpec:
    multiVm:
      tiers:
      - name: mariadb
        title: MariaDBCluster
        bootDisk:
          diskSize:
            defaultSizeGb: 10
            minSizeGb: 10
          diskType:
            defaultType: pd-standard
        gceMetadataItems:
        - key: ENV_MARIADB_NODE_HOSTNAMES
          tierVmNames:
            tier: mariadb
            allVms:
              delimiter: '|'
        - key: MYSQL_ROOT_ANYWHERE_ALLOW
          valueFromDeployInputField: rootFromAnywhere
        - key: MYSQL_DATABASE
          value: 'example_database'
        firewallRules:
        - port: '3306'
          protocol: TCP
        - port: '22'
          protocol: TCP
        - protocol: ICMP
        images:
        - name: imageName # {"$ref":"#/definitions/io.k8s.cli.setters.image"}
          project: projectId # {"$ref":"#/definitions/io.k8s.cli.setters.projectId"}
        instanceCount:
          defaultValue: 3 # {"$ref":"#/definitions/io.k8s.cli.setters.defaultReplicas"}
          range:
            startValue: 1
            endValue: 10
        machineType:
          defaultMachineType:
            gceMachineType: e2-standard-2
          minimum:
            cpu: 1
            ramGb: 1.69
        applicationStatus:
          type: WAITER
          waiter:
            waiterTimeoutSecs: 600
        networkInterfaces:
          minCount: 1
          maxCount: 8
          externalIp:
            defaultType: EPHEMERAL
      deployInput:
        sections:
        - placement: MAIN
          fields:
          - name: rootFromAnywhere
            title: Root from anywhere
            tooltip: Allow root user authorization from anywhere. By default it possible
              only from localhost
            required: true
            booleanCheckbox: {}

      passwords:
      - allowSpecialChars: true
        displayLabel: MariaDB
        length: 14
        metadataKey: MYSQL_ROOT_PASSWORD
        username: root
      - allowSpecialChars: true
        displayLabel: MariaDB replication
        length: 14
        metadataKey: MYSQL_REPLICATION_PASSWORD
        username: replication

      stackdriver:
        logging:
          defaultOn: false
        monitoring:
          defaultOn: false

      postDeploy:
        actionItems:
        # SSH through an external IP
        - heading: Connect to the MariaDB primary server
          description: The initial Maria primary server is
            {{ outputs().mariadb_vmName0 }}; use the gcloud command below
            to connect.
          snippet: gcloud compute ssh {{ outputs().mariadb_vmName0 }} --project
            {{ outputs().project}} --zone {{ properties().zone }}
          showIf:
            hasExternalIp:
              tier: mariadb
