apiVersion: dev.marketplace.cloud.google.com/v1alpha1
kind: SaasListingTemplate
credFilePath: cred.json
integrationTestConfig:
  provider: "providers/e2e-testing"
  productExternalName: "procurement-ingestion-enabled-tester-with-subscription-usage.endpoints.cloud-marketplace-testing.cloud.goog"
  billingAccount: "billingAccounts/000000-000000-000000"
  plans: ["plan-a", "plan-d"]
  approveEntitlementTimeoutSeconds: 600
  approvePlanChangeTimeoutSeconds: 600
  billingMeteringTestConfig:
    - driver:
        driverCommand: "docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/saas:/keys -e GOOGLE_APPLICATION_CREDENTIALS=/keys/cred.json -e GOOGLE_CLOUD_PROJECT=testing-producer-saas gcr.io/marketplace-saas-tools/billing-metering-driver --service=procurement-ingestion-enabled-tester-with-subscription-usage.endpoints.cloud-marketplace-testing.cloud.goog --metric=procurement-ingestion-enabled-tester-with-subscription-usage.endpoints.cloud-marketplace-testing.cloud.goog/plan_a_metric_1 --consumer_id=project_number:000000000000"
        planId: "plan-a"
        billingMeteringConfigPath: "/tmp/saas/expectations.textproto"
